### ISSUE TITLE
[Feature Request] Allow specifying existing input/output types

### ISSUE THREAD

**Issue by khionu** [eugene-babichenko/rust-fsm#10]
I'm making a parser that uses `rust-fsm` to guide the consumption of my token stream. It'd be convenient if I could have my FSM use my TokenType as the input.

A catch is that the input type would have to be an enum without constructors, however a derive should be able to verify that that is the case. Alternatively, simply document that the DSL will assume it is.

**Comment by eugene-babichenko** [comment]
So, an example code would be something like:

```rust
enum CustomInput {}

state_machine! {
    Machine(InitialState)
}
```

right?

**Comment by khionu** [comment]
That would work, yes!

**Comment by khionu** [comment]
Though, the same for output types would be appreciated. I think it's fine for this crate to simply assume the output types are enums without fields
