### ISSUE TITLE
Upgrade `quote` and `syn` to v1.x

### ISSUE THREAD

**Issue by jiangliu** [eugene-babichenko/rust-fsm#5]
The rust-fsm-dsl crate depends on `quote` and `syn` 0.x versions, and most other clients of `quote` and `syn` crates have upgraded to 1.x versions. So it would be better to upgrade to 1.x to avoid multiple versions of dependent crates.

**Comment by eugene-babichenko** [comment]
Closed in the latest release.

**Comment by eugene-babichenko** [comment]
https://github.com/eugene-babichenko/rust-fsm/releases/tag/v0.6.0
